version: 1

models:
    - name: dim_customers
      description:"Defining dimesions of a customer"
      columns:
          - name: customer_id
            description:
            tests: 
                - not null
